// Данные библиотеки - ВЕРСИЯ 4.1
// Всего: 60 уникальных книг
// Новое: номера на полке, авторы в формате "Фамилия Имя"
const books = [
    {
        id: 1,
        shelfNumber: 1,
        title: 'Главный учебник HR в мире',
        author: 'Армстронг Майкл',
        publisher: 'Бомбора',
        year: 2020,
        isbn: '978-5-04-155820-8',
        genres: ['Бизнес', 'HR', 'Управление персоналом'],
        genreKeys: ['business'],
        cover: './images/covers/book-001.jpg',
        description: 'Фундаментальное руководство по управлению человеческими ресурсами, признанное во всем мире. Эта книга содержит проверенные практики и современные подходы к управлению персоналом в организациях любого масштаба.',
        series: null
    },
    {
        id: 2,
        shelfNumber: 2,
        title: 'Безграничный разум',
        author: 'Боулер Джо',
        publisher: 'Манн, Иванов и Фербер',
        year: 2020,
        isbn: null,
        genres: ['Психология', 'Саморазвитие', 'Образование'],
        genreKeys: ['psychology', 'education'],
        cover: './images/covers/book-002.jpg',
        description: 'Книга о том, как развить потенциал своего разума и преодолеть ограничивающие убеждения. Автор предлагает научно обоснованные методы развития когнитивных способностей и формирования установки на рост.',
        series: 'Библиотека Сбербанка, том 96'
    },
    {
        id: 3,
        shelfNumber: 3,
        title: 'Работа, которая заряжает',
        subtitle: 'Как не выгореть, занимаясь любимым делом',
        author: 'Резанова Елена',
        publisher: 'Манн, Иванов и Фербер',
        year: 2022,
        isbn: null,
        genres: ['Психология', 'Карьера', 'Саморазвитие'],
        genreKeys: ['psychology', 'career'],
        cover: './images/covers/book-003.jpg',
        description: 'Практическое руководство по профилактике профессионального выгорания. Автор делится эффективными техниками поддержания энергии и мотивации в работе, помогая найти баланс между продуктивностью и личным благополучием.',
        series: 'Измени свою жизнь'
    },
    {
        id: 4,
        shelfNumber: 4,
        title: 'Думай и предпринимай',
        author: 'Цаплина Ольга',
        publisher: 'Бомбора',
        year: 2024,
        isbn: null,
        genres: ['Бизнес', 'Предпринимательство'],
        genreKeys: ['business'],
        cover: './images/covers/book-004.jpg',
        description: 'Практическое руководство для предпринимателей о том, как думать и действовать эффективно в бизнесе.',
        series: null
    },
    {
        id: 5,
        shelfNumber: 5,
        title: 'Игры. Обучение. Тренинг. Досуг',
        author: 'Коллектив авторов',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Обучение', 'Тренинг', 'Психология'],
        genreKeys: ['education', 'psychology'],
        cover: './images/covers/book-005.jpg',
        description: 'Сборник игр для интенсивного обучения, активного отдыха, коммуникативно-лингвистических и психотехнических игр. Включает игры для работы с текстом, деловые тренинги, игры-тесты и методики саморегуляции.',
        series: null
    },
    {
        id: 6,
        shelfNumber: 6,
        title: 'Отличная память в любом возрасте',
        subtitle: 'Как укрепить память и повысить умственные способности',
        author: 'Перлмуттер Дэвид, Коулмэн Кэрол',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Психология', 'Саморазвитие', 'Здоровье'],
        genreKeys: ['psychology'],
        cover: './images/covers/book-006.jpg',
        description: 'Научно обоснованные методы укрепления памяти и повышения умственных способностей в любом возрасте.',
        series: null
    },
    {
        id: 7,
        shelfNumber: 7,
        title: 'Фокусы мерчандайзинга',
        subtitle: 'Эффективные "трюки" для торговцев и поставщиков',
        author: 'Гузелевич Наталия',
        publisher: 'Питер',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Маркетинг', 'Продажи'],
        genreKeys: ['business'],
        cover: './images/covers/book-007.jpg',
        description: 'Практические приемы и стратегии мерчандайзинга для эффективной выкладки товаров и увеличения продаж.',
        series: null
    },
    {
        id: 8,
        shelfNumber: 8,
        title: 'Конкурентное сотрудничество в бизнесе',
        subtitle: 'Co-opetition',
        author: 'Бранденбургер Адам, Нейлбафф Барри',
        publisher: 'Кейс',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Стратегия', 'Менеджмент'],
        genreKeys: ['business'],
        cover: './images/covers/book-008.jpg',
        description: 'Революционный подход к бизнес-стратегии, объединяющий конкуренцию и сотрудничество для создания новых возможностей.',
        series: null
    },
    {
        id: 9,
        shelfNumber: 9,
        title: 'Никогда не ешьте в одиночку',
        subtitle: 'И другие правила нетворкинга',
        author: 'Феррацци Кейт, Рэз Тал',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Нетворкинг', 'Карьера'],
        genreKeys: ['business', 'career'],
        cover: './images/covers/book-009.jpg',
        description: 'Практическое руководство по построению эффективных деловых связей и развитию профессиональной сети контактов.',
        series: null
    },
    {
        id: 10,
        shelfNumber: 10,
        title: 'Бюджетирование как инструмент управления',
        subtitle: 'Книга 1',
        author: 'Карпов Александр',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Финансы', 'Управление'],
        genreKeys: ['business'],
        cover: './images/covers/book-010.jpg',
        description: 'Первая книга из серии "100% практического бюджетирования" - практическое руководство по внедрению бюджетирования в компании.',
        series: 'Серия книг "100% практического бюджетирования"'
    },
    {
        id: 11,
        shelfNumber: 11,
        title: 'Управляя изменениями',
        subtitle: 'Как эффективно управлять изменениями в обществе, бизнесе и личной жизни',
        author: 'Адизес Ицхак Кальдерон',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Менеджмент', 'Изменения'],
        genreKeys: ['business'],
        cover: './images/covers/book-011.jpg',
        description: 'Методология Адизеса по управлению организационными изменениями и трансформацией компаний.',
        series: 'Методология Адизеса'
    },
    {
        id: 12,
        shelfNumber: 12,
        title: 'Ведение бизнеса: Ключевые понятия',
        author: 'Сазерленд Джонатан, Кэнуэлл Дайан',
        publisher: 'Balance Business Books',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Менеджмент'],
        genreKeys: ['business'],
        cover: './images/covers/book-012.jpg',
        description: 'Справочник ключевых понятий и концепций ведения бизнеса для руководителей и предпринимателей.',
        series: null
    },
    {
        id: 13,
        shelfNumber: 13,
        title: 'Управление программами проектов на основе стандарта PMI',
        subtitle: 'Изложение методологии и рекомендации по применению',
        author: 'Павлов А. Н.',
        publisher: 'Бином',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Проектное управление', 'PMI'],
        genreKeys: ['business'],
        cover: './images/covers/book-013.jpg',
        description: 'Профессиональное руководство по управлению программами и проектами на основе стандарта PMI.',
        series: 'Проекты Программы Портфели'
    },
    {
        id: 14,
        shelfNumber: 14,
        title: 'Искусство вовлечения',
        subtitle: 'Как максимально полно раскрыть потенциал своих сотрудников',
        author: 'Хоуден Джим',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'HR', 'Менеджмент'],
        genreKeys: ['business'],
        cover: './images/covers/book-014.jpg',
        description: 'Проверенные методы успешного вовлечения сотрудников на каждом уровне организации.',
        series: 'Менеджмент — твоя работа'
    },
    {
        id: 15,
        shelfNumber: 15,
        title: 'Мастерство учителя',
        subtitle: 'Проверенные методики выдающихся преподавателей',
        author: 'Лемов Дуг',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Образование', 'Обучение', 'Методика'],
        genreKeys: ['education'],
        cover: './images/covers/book-015.jpg',
        description: 'Сборник эффективных методик преподавания от лучших учителей со всего мира.',
        series: null
    },
    {
        id: 16,
        shelfNumber: 16,
        title: 'Шесть дисциплин прорывного обучения',
        subtitle: 'Как превратить обучение и развитие в бизнес-результаты',
        author: 'Поллок Рой В. Х., Джефферсон Эндрю МакК., Уик Кэлхун У.',
        publisher: 'Сбербанк Корпоративный университет',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Обучение', 'HR'],
        genreKeys: ['business', 'education'],
        cover: './images/covers/book-016.jpg',
        description: 'Методология превращения корпоративного обучения в измеримые бизнес-результаты.',
        series: null
    },
    {
        id: 17,
        shelfNumber: 17,
        title: 'Новые лидеры российского бизнеса',
        author: 'Кетс де Врис М., Шекшня С., Коротов К., Флорент-Трейси Э.',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Лидерство', 'Менеджмент'],
        genreKeys: ['business'],
        cover: './images/covers/book-017.jpg',
        description: 'Истории и опыт современных российских бизнес-лидеров, их подходы к управлению и развитию компаний.',
        series: null
    },
    {
        id: 18,
        shelfNumber: 18,
        title: 'Не в знании сила',
        subtitle: 'Как сомнения помогают нам развиваться',
        author: 'Д\'Соуза Стивен, Реннер Дайана',
        publisher: 'Альпина Паблишер',
        year: null,
        isbn: null,
        genres: ['Психология', 'Саморазвитие', 'Бизнес'],
        genreKeys: ['psychology', 'business'],
        cover: './images/covers/book-018.jpg',
        description: 'Книга о том, как признание своего незнания и сомнения могут стать ключом к инновациям и личному росту.',
        series: null
    },
    {
        id: 19,
        shelfNumber: 19,
        title: 'Менталист. Чтение мыслей',
        subtitle: 'Примеры и упражнения',
        author: 'Хавенер Торстен',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Психология', 'Коммуникация'],
        genreKeys: ['psychology'],
        cover: './images/covers/book-019.jpg',
        description: 'Практические упражнения по развитию навыков наблюдения, интуиции и понимания невербальных сигналов.',
        series: null
    },
    {
        id: 20,
        shelfNumber: 20,
        title: 'Организационная культура и эффективность бизнеса',
        author: 'Малинин Е.Д.',
        publisher: 'Московский психолого-социальный институт',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Организационная культура', 'Менеджмент'],
        genreKeys: ['business'],
        cover: './images/covers/book-020.jpg',
        description: 'Исследование влияния организационной культуры на эффективность бизнеса и методы ее формирования.',
        series: null
    },
    {
        id: 21,
        shelfNumber: 21,
        title: 'Кратко о психике',
        subtitle: 'Учебное пособие (Для широкого круга читателей)',
        author: 'Климов Е. А.',
        publisher: 'Московский психолого-социальный институт',
        year: null,
        isbn: null,
        genres: ['Психология', 'Образование'],
        genreKeys: ['psychology', 'education'],
        cover: './images/covers/book-021.jpg',
        description: 'Доступное введение в основы психологии и понимание психических процессов.',
        series: null
    },
    {
        id: 22,
        shelfNumber: 22,
        title: 'Кибербезопасность: правила игры',
        subtitle: 'Как руководители и сотрудники влияют на культуру безопасности в компании',
        author: 'Сэрра Эллисон',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Кибербезопасность', 'IT'],
        genreKeys: ['business'],
        cover: './images/covers/book-022.jpg',
        description: 'Практическое руководство по формированию культуры кибербезопасности в организации.',
        series: null
    },
    {
        id: 23,
        shelfNumber: 23,
        title: 'Прототипирование',
        subtitle: 'Практическое руководство',
        author: 'Варфел Тодд Заки',
        publisher: 'Rosenfeld',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Дизайн', 'UX'],
        genreKeys: ['business'],
        cover: './images/covers/book-023.jpg',
        description: 'Рекомендовано РБК. Практическое руководство по созданию прототипов продуктов и сервисов.',
        series: null
    },
    {
        id: 24,
        shelfNumber: 24,
        title: 'Цифровая трансформация Китая',
        author: 'Ма Хуатэн, Мэнь Чжаоли, Ян Дели, Ван Хуалей',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Технологии', 'Экономика'],
        genreKeys: ['business'],
        cover: './images/covers/book-024.jpg',
        description: 'Анализ цифровой трансформации экономики Китая и уроки для мирового бизнеса.',
        series: null
    },
    {
        id: 25,
        shelfNumber: 25,
        title: 'Assessment Center для руководителей',
        subtitle: 'Опыт реализации в российской компании, упражнения, кейсы',
        author: 'Красностанова М. В., Осетрова Н. В., Самара Н. В.',
        publisher: 'Вершина',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'HR', 'Оценка персонала'],
        genreKeys: ['business'],
        cover: './images/covers/book-025.jpg',
        description: 'Практический опыт внедрения и проведения центров оценки для руководителей в российских компаниях.',
        series: null
    },
    {
        id: 26,
        shelfNumber: 26,
        title: 'Как составить наилучший бизнес-план',
        subtitle: 'Для любой отрасли и сферы деятельности',
        author: 'Абрамс Ронда',
        publisher: 'Современные Бизнес-Технологии',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Планирование', 'Предпринимательство'],
        genreKeys: ['business'],
        cover: './images/covers/book-026.jpg',
        description: 'Forbes и Стэнфордская школа бизнеса рекомендуют. Пятое международное издание практического руководства по составлению бизнес-планов.',
        series: null
    },
    {
        id: 27,
        shelfNumber: 27,
        title: 'Стратегическая карта, системный подход и KPI',
        subtitle: 'Инструменты для руководителей',
        author: 'Ветлужских Елена',
        publisher: 'Альпина Бизнес Букс',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Стратегия', 'Менеджмент'],
        genreKeys: ['business'],
        cover: './images/covers/book-027.jpg',
        description: 'Практические инструменты для разработки стратегии и системы KPI в организации.',
        series: null
    },
    {
        id: 28,
        shelfNumber: 28,
        title: 'Убеждай и побеждай',
        subtitle: 'Секреты эффективной аргументации',
        author: 'Непряхин Никита',
        publisher: 'Альпина Паблишер',
        year: null,
        isbn: null,
        genres: ['Психология', 'Коммуникация', 'Бизнес'],
        genreKeys: ['psychology', 'business'],
        cover: './images/covers/book-028.jpg',
        description: 'Практическое руководство по искусству аргументации и убеждения с предисловием Радислава Гандапаса.',
        series: null
    },
    {
        id: 29,
        shelfNumber: 29,
        title: 'Коучинг. Повышайте собственную эффективность',
        author: 'Ландсберг Макс',
        publisher: 'Эксмо',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Коучинг', 'Саморазвитие'],
        genreKeys: ['business'],
        cover: './images/covers/book-029.jpg',
        description: 'Международный бестселлер по коучингу. Практические методы повышения эффективности в работе и жизни.',
        series: 'Дао успешного бизнесмена'
    },
    {
        id: 30,
        shelfNumber: 30,
        title: 'Осторожно - острый ум!',
        subtitle: 'Золотые россыпи афоризмов',
        author: 'Сидоров Сергей, Георгиев Веселин',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Юмор', 'Афоризмы'],
        genreKeys: ['business'],
        cover: './images/covers/book-030.jpg',
        description: 'Сборник задоринок и смехариков - остроумных афоризмов и цитат.',
        series: null
    },
    {
        id: 31,
        shelfNumber: 31,
        title: 'Финансы, денежное обращение и кредит',
        author: 'Галанов В.А.',
        publisher: 'Форум',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Финансы', 'Экономика'],
        genreKeys: ['business'],
        cover: './images/covers/book-031.jpg',
        description: 'Учебное пособие для профессионального образования в области финансов и банковского дела.',
        series: 'Профессиональное образование'
    },
    {
        id: 32,
        shelfNumber: 32,
        title: 'Взлом креатива',
        subtitle: 'Как увидеть то, что не видят другие',
        author: 'Микалко Майкл',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Психология', 'Креативность', 'Саморазвитие'],
        genreKeys: ['psychology'],
        cover: './images/covers/book-032.jpg',
        description: 'Методы развития креативного мышления и способности видеть нестандартные решения.',
        series: null
    },
    {
        id: 33,
        shelfNumber: 33,
        title: 'У каждого свой Эверест',
        subtitle: 'Как опыт реальных восхождений помогает вдохновлять команды и управлять проектами',
        author: 'Кофанов Сергей',
        publisher: 'Бомбора',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Менеджмент', 'Лидерство'],
        genreKeys: ['business'],
        cover: './images/covers/book-033.jpg',
        description: 'Уроки альпинизма и реальных восхождений применительно к управлению командами и проектами.',
        series: null
    },
    {
        id: 34,
        shelfNumber: 34,
        title: 'Думай как дизайнер',
        subtitle: 'Дизайн-мышление для менеджеров',
        author: 'Лиатка Жанна, Огилви Тим',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Дизайн-мышление', 'Инновации'],
        genreKeys: ['business'],
        cover: './images/covers/book-034.jpg',
        description: 'Практическое руководство по применению дизайн-мышления в управлении и бизнесе.',
        series: null
    },
    {
        id: 35,
        shelfNumber: 35,
        title: 'Спиральная динамика',
        subtitle: 'Управляя ценностями, лидерством и изменениями в XXI веке',
        author: 'Бек Дон, Кован Крис',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Психология', 'Менеджмент'],
        genreKeys: ['business', 'psychology'],
        cover: './images/covers/book-035.jpg',
        description: 'Теория спиральной динамики применительно к управлению организациями и социальным изменениям.',
        series: 'Серия Advanced Management Institute'
    },
    {
        id: 36,
        shelfNumber: 36,
        title: 'Формула времени',
        subtitle: 'Тайм-менеджмент на Outlook 2007',
        author: 'Архангельский Глеб',
        publisher: 'Microsoft',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Тайм-менеджмент', 'Продуктивность'],
        genreKeys: ['business'],
        cover: './images/covers/book-036.jpg',
        description: 'Практическое руководство по тайм-менеджменту с использованием Microsoft Outlook 2007 от российского эксперта в области управления временем.',
        series: null
    },
    {
        id: 37,
        shelfNumber: 37,
        title: 'Техники подбора персонала',
        subtitle: 'Искусство находить лучших',
        author: 'Дубиненкова Е. Н.',
        publisher: 'Речь',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'HR', 'Рекрутинг'],
        genreKeys: ['business'],
        cover: './images/covers/book-037.jpg',
        description: 'Психологический тренинг по эффективным техникам подбора персонала. Как сделать подбор персонала максимально эффективным?',
        series: 'Психологический тренинг'
    },
    {
        id: 38,
        shelfNumber: 38,
        title: 'Озадачник',
        subtitle: '133 вопроса на знание логики, математики и физики',
        author: 'Полуэктов Павел, Полуэктов Николай',
        publisher: 'Альпина Паблишер',
        year: null,
        isbn: null,
        genres: ['Образование', 'Логика', 'Математика'],
        genreKeys: ['education'],
        cover: './images/covers/book-038.jpg',
        description: 'Editor\'s Choice. Сборник интересных задач и вопросов для развития логического мышления, математических и физических знаний.',
        series: null
    },
    {
        id: 39,
        shelfNumber: 39,
        title: 'Оценка качества менеджмента компаний',
        subtitle: 'Учебное пособие',
        author: 'Шокина Л. И.',
        publisher: 'КНОРУС',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Менеджмент', 'Оценка'],
        genreKeys: ['business'],
        cover: './images/covers/book-039.jpg',
        description: 'Учебное пособие Финансовой академии при Правительстве РФ по методам оценки качества управления компаниями.',
        series: null
    },
    {
        id: 40,
        shelfNumber: 40,
        title: 'Современная практика корпоративного управления в российских компаниях',
        subtitle: 'Руководство для директора',
        author: 'Ассоциация независимых директоров',
        publisher: 'Альпина Бизнес Букс',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Корпоративное управление', 'Менеджмент'],
        genreKeys: ['business'],
        cover: './images/covers/book-040.jpg',
        description: 'Опыт, приносящий успех. Практическое руководство по современному корпоративному управлению в российских компаниях.',
        series: 'Опыт, приносящий успех'
    },
    {
        id: 41,
        shelfNumber: 41,
        title: 'Говорить "нет" не испытывая чувства вины',
        author: 'Шейнов Виктор',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Психология', 'Коммуникация', 'Саморазвитие'],
        genreKeys: ['psychology'],
        cover: './images/covers/book-041.jpg',
        description: 'Практические техники и стратегии для уверенного отказа без чувства вины. Как научиться говорить "нет" и отстаивать свои границы.',
        series: null
    },
    {
        id: 42,
        shelfNumber: 42,
        title: 'Юридический минимум',
        subtitle: 'Главное, что нужно знать руководителю и бизнесмену',
        author: 'Мельников Алексей, Тихонов Дмитрий',
        publisher: 'Альпина Бизнес Букс',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Право', 'Юриспруденция'],
        genreKeys: ['business'],
        cover: './images/covers/book-042.jpg',
        description: 'Необходимый минимум юридических знаний для руководителей и предпринимателей. Основы правовых аспектов ведения бизнеса.',
        series: null
    },
    {
        id: 43,
        shelfNumber: 43,
        title: 'Инструменты управления персоналом',
        subtitle: 'Аспекты кадрового документооборота',
        author: 'Коллектив авторов',
        publisher: 'Берег А',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'HR', 'Кадровое делопроизводство'],
        genreKeys: ['business'],
        cover: './images/covers/book-043.jpg',
        description: 'Практическое руководство по кадровому документообороту и инструментам управления персоналом.',
        series: null
    },
    {
        id: 44,
        shelfNumber: 44,
        title: 'Как измерить HR-менеджмент',
        subtitle: 'Третье издание',
        author: 'Фиц-Энц Жак, Дэвисон Барбара',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'HR', 'Метрики'],
        genreKeys: ['business'],
        cover: './images/covers/book-044.jpg',
        description: 'Классическое руководство по измерению эффективности HR-функции. Методы и метрики для оценки работы службы персонала.',
        series: null
    },
    {
        id: 45,
        shelfNumber: 45,
        title: 'Классические работы по менеджменту',
        author: 'Друкер Питер',
        publisher: 'Сколково, Ведомости',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Менеджмент', 'Классика'],
        genreKeys: ['business'],
        cover: './images/covers/book-045.jpg',
        description: 'Сборник классических работ легендарного теоретика менеджмента Питера Друкера. Фундаментальные идеи об управлении организациями.',
        series: null
    },
    {
        id: 46,
        shelfNumber: 46,
        title: 'Сила в спокойствии',
        subtitle: 'Достижение гармонии с помощью трансцендентальной медитации',
        author: 'Рот Боб',
        publisher: 'Альпина Паблишер',
        year: null,
        isbn: null,
        genres: ['Психология', 'Медитация', 'Саморазвитие'],
        genreKeys: ['psychology'],
        cover: './images/covers/book-046.jpg',
        description: 'Бестселлер The New York Times. Практическое руководство по трансцендентальной медитации для достижения гармонии и снятия стресса.',
        series: null
    },
    {
        id: 47,
        shelfNumber: 47,
        title: 'От носорога к единорогу',
        subtitle: 'Как провести компанию через трансформацию в цифровую эпоху и избежать смертельных ловушек',
        author: 'Орловский Виктор, Коровкин Владимир',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Цифровая трансформация', 'Стартапы'],
        genreKeys: ['business'],
        cover: './images/covers/book-047.jpg',
        description: 'Практическое руководство по трансформации традиционного бизнеса в успешную цифровую компанию-единорога.',
        series: null
    },
    {
        id: 48,
        shelfNumber: 48,
        title: 'Компания - создатель знания',
        subtitle: 'Зарождение и развитие инноваций в японских фирмах',
        author: 'Нонака И., Такеучи Х.',
        publisher: 'Олимп-Бизнес',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Инновации', 'Менеджмент'],
        genreKeys: ['business'],
        cover: './images/covers/book-048.jpg',
        description: 'Классическое исследование о том, как японские компании создают и используют знания для инноваций.',
        series: null
    },
    {
        id: 49,
        shelfNumber: 49,
        title: 'Развитие потенциала сотрудников',
        subtitle: 'Профессиональные компетенции. Лидерство, коммуникации',
        author: 'Иванова Светлана, Болдогеев Дмитрий, Борчанинова Эмма, Глотова Анна, Жигилий Оксана',
        publisher: 'Альпина Бизнес Букс',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'HR', 'Управление персоналом'],
        genreKeys: ['business'],
        cover: './images/covers/book-049.jpg',
        description: 'От автора бестселлеров "Искусство подбора персонала" и "Мотивация на 100%". Развитие профессиональных компетенций сотрудников.',
        series: null
    },
    {
        id: 50,
        shelfNumber: 50,
        title: 'Психологический тренинг в группе',
        author: null,
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Психология', 'Обучение', 'Тренинги'],
        genreKeys: ['psychology', 'education'],
        cover: './images/covers/book-050.jpg',
        description: 'Учебное пособие по проведению психологических тренингов в группах.',
        series: null
    },
    {
        id: 51,
        shelfNumber: 51,
        title: 'Договориться можно обо всём!',
        subtitle: 'Как добиваться максимума в любых переговорах',
        author: 'Кеннеди Гэвин',
        publisher: 'Альпина Бизнес Букс',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Переговоры', 'Коммуникации'],
        genreKeys: ['business'],
        cover: './images/covers/book-051.jpg',
        description: 'Практическое руководство по эффективным переговорам и достижению максимальных результатов в любых ситуациях.',
        series: null
    },
    {
        id: 52,
        shelfNumber: 52,
        title: 'Эффективный воркшоп',
        subtitle: 'Все о психологической группе',
        author: 'Фопель К.',
        publisher: 'Генезис',
        year: null,
        isbn: null,
        genres: ['Психология', 'Обучение', 'Тренинги'],
        genreKeys: ['psychology', 'education'],
        cover: './images/covers/book-052.jpg',
        description: 'Комплексное руководство по организации и проведению эффективных психологических воркшопов и групповой работы.',
        series: null
    },
    {
        id: 53,
        shelfNumber: 53,
        title: 'Дело не в кофе',
        subtitle: 'Корпоративная культура Starbucks',
        author: 'Бехар Говард',
        publisher: 'Альпина Бизнес Букс',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Корпоративная культура', 'Менеджмент'],
        genreKeys: ['business'],
        cover: './images/covers/book-053.jpg',
        description: 'Инсайдерский взгляд на корпоративную культуру Starbucks от бывшего президента компании. С предисловием Говарда Шульца.',
        series: 'The Moscow Times recommends'
    },
    {
        id: 54,
        shelfNumber: 54,
        title: 'Большая книга лучших игр и упражнений',
        subtitle: 'для любого тренинга',
        author: 'Кипнис Михаил',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Психология', 'Обучение', 'Тренинги'],
        genreKeys: ['psychology', 'education'],
        cover: './images/covers/book-054.jpg',
        description: 'Коллекция лучших игр и упражнений для проведения любых тренингов.',
        series: 'Психология. Высший курс'
    },
    {
        id: 55,
        shelfNumber: 55,
        title: 'Занимательная психология',
        author: null,
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Психология'],
        genreKeys: ['psychology'],
        cover: './images/covers/book-055.jpg',
        description: 'Увлекательное введение в мир психологии через интересные факты и эксперименты.',
        series: 'Х файлы'
    },
    {
        id: 56,
        shelfNumber: 56,
        title: 'Корпоративные игры',
        subtitle: 'Пособие по выживанию',
        author: 'Гриффин Джерри, Паркер Сайран',
        publisher: 'Вершина',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Карьера', 'Корпоративная культура'],
        genreKeys: ['business', 'career'],
        cover: './images/covers/book-056.jpg',
        description: 'Практическое руководство по навигации в корпоративной среде и выживанию в офисной политике.',
        series: null
    },
    {
        id: 57,
        shelfNumber: 57,
        title: '5S для офиса',
        subtitle: 'Как организовать эффективное рабочее место',
        author: 'Фабрицио Том, Тэппинг Дон',
        publisher: 'Институт комплексных стратегических исследований',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Продуктивность', 'Организация'],
        genreKeys: ['business'],
        cover: './images/covers/book-057.jpg',
        description: 'Применение японской системы 5S для организации эффективного рабочего пространства в офисе.',
        series: null
    },
    {
        id: 58,
        shelfNumber: 58,
        title: 'Тренинги - это классно',
        subtitle: 'Стратегия проведения психологических тренингов',
        author: 'Вагин Игорь, Рипинская Павла',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Психология', 'Обучение', 'Тренинги'],
        genreKeys: ['psychology', 'education'],
        cover: './images/covers/book-058.jpg',
        description: 'Каждый человек обладает поистине безграничным потенциалом, и главное для тренера — этот потенциал раскрыть!',
        series: null
    },
    {
        id: 59,
        shelfNumber: 59,
        title: 'Академия продаж',
        author: 'Вагин Игорь, Рипинская Павла',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Продажи', 'Коммуникации'],
        genreKeys: ['business'],
        cover: './images/covers/book-059.jpg',
        description: 'Эффективные продажи — это искусство, которому можно научиться. Масса конкретных рекомендаций по продажам в различных секторах рынка.',
        series: null
    },
    {
        id: 60,
        shelfNumber: 60,
        title: 'Тренинг для тренеров на 100%',
        author: 'Чуркина Мария, Жадько Наталья',
        publisher: 'Альпина Бизнес Букс',
        year: 2005,
        isbn: null,
        genres: ['Образование', 'Обучение', 'Тренинги'],
        genreKeys: ['education', 'psychology'],
        cover: './images/covers/book-060.jpg',
        description: 'Секреты интенсивного обучения. Практическое руководство для тренеров по проведению эффективных обучающих программ.',
        series: null
    }
];
